//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneManagement.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneManagement.Common.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm điện thoại thành công!.
        /// </summary>
        public static string AddPhoneSuccess {
            get {
                return ResourceManager.GetString("AddPhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới điện thoại.
        /// </summary>
        public static string AddPhoneTitle {
            get {
                return ResourceManager.GetString("AddPhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt thành công!.
        /// </summary>
        public static string ApprovePhoneSuccess {
            get {
                return ResourceManager.GetString("ApprovePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa điện thoại {0}?.
        /// </summary>
        public static string ConfirmDeletePhone {
            get {
                return ResourceManager.GetString("ConfirmDeletePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công!.
        /// </summary>
        public static string DeletePhoneSuccess {
            get {
                return ResourceManager.GetString("DeletePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa điện thoại.
        /// </summary>
        public static string EditPhoneTitle {
            get {
                return ResourceManager.GetString("EditPhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: {0}.
        /// </summary>
        public static string ErrorMessagePrefix {
            get {
                return ResourceManager.GetString("ErrorMessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá không hợp lệ..
        /// </summary>
        public static string InvalidPrice {
            get {
                return ResourceManager.GetString("InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng tồn kho không hợp lệ..
        /// </summary>
        public static string InvalidStock {
            get {
                return ResourceManager.GetString("InvalidStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model không được để trống..
        /// </summary>
        public static string ModelCannotBeEmpty {
            get {
                return ResourceManager.GetString("ModelCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang {0} / {1} ({2}/{3} bản ghi).
        /// </summary>
        public static string PageInfoFormat {
            get {
                return ResourceManager.GetString("PageInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi không tồn tại!.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy duyệt thành công!.
        /// </summary>
        public static string RejectPhoneSuccess {
            get {
                return ResourceManager.GetString("RejectPhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một điện thoại để duyệt..
        /// </summary>
        public static string SelectPhoneToApprove {
            get {
                return ResourceManager.GetString("SelectPhoneToApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một điện thoại để xóa..
        /// </summary>
        public static string SelectPhoneToDelete {
            get {
                return ResourceManager.GetString("SelectPhoneToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một điện thoại để hủy duyệt..
        /// </summary>
        public static string SelectPhoneToReject {
            get {
                return ResourceManager.GetString("SelectPhoneToReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một điện thoại để cập nhật..
        /// </summary>
        public static string SelectPhoneToUpdate {
            get {
                return ResourceManager.GetString("SelectPhoneToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một điện thoại để xem chi tiết..
        /// </summary>
        public static string SelectPhoneToViewDetail {
            get {
                return ResourceManager.GetString("SelectPhoneToViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không xác định.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công!.
        /// </summary>
        public static string UpdatePhoneSuccess {
            get {
                return ResourceManager.GetString("UpdatePhoneSuccess", resourceCulture);
            }
        }
    }
}
